import { useMemo, useState } from 'react';
import { AlertTriangle, ArrowUpRight, Building2, Download, Network, Plus } from 'lucide-react';
import { toast } from 'sonner';
import api from '../../api/api';
import { encodeCsvCell } from '../../lib/spreadsheetSecurity';
import { Badge } from '../ui/badge';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';

const title = (value) => String(value || '').replaceAll('_', ' ').toLowerCase().replace(/(^|\s)\S/g, (letter) => letter.toUpperCase());
const money = (value) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(Number(value || 0));
const Field = ({ label, children }) => <div className="space-y-1.5"><Label className="text-[11px] font-medium text-mr-muted">{label}</Label>{children}</div>;

const INITIAL = {
  mode: 'GROUP', group_code: '', legal_name: '', entity_code: '', entity_type: 'COMPANY', developer_group_id: 'none',
  group_id: '', organization_id: '', site_id: '', legal_entity_id: '', relationship_type: 'PROJECT_OWNER', effective_from: new Date().toISOString().slice(0, 10),
};

export default function EnterprisePortfolioPanel({ enterprise, portfolio, sites, organizationId, onReload }) {
  const [form, setForm] = useState(INITIAL);
  const [saving, setSaving] = useState(false);
  const pendingGroups = useMemo(() => (enterprise.groups || []).filter((group) => group.organizations?.some((item) => Number(item.organization_id) === Number(organizationId) && item.relationship_status === 'PENDING')), [enterprise.groups, organizationId]);
  const ownedGroups = useMemo(() => (enterprise.groups || []).filter((group) => Number(group.owner_organization_id) === Number(organizationId)), [enterprise.groups, organizationId]);

  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event) => {
    event.preventDefault(); setSaving(true);
    try {
      if (form.mode === 'GROUP') await api.post('/phase4/admin/enterprise/groups', { group_code: form.group_code, legal_name: form.legal_name });
      if (form.mode === 'ENTITY') await api.post('/phase4/admin/enterprise/legal-entities', { entity_code: form.entity_code, legal_name: form.legal_name, entity_type: form.entity_type, developer_group_id: form.developer_group_id === 'none' ? null : Number(form.developer_group_id) });
      if (form.mode === 'GROUP_INVITE') await api.post(`/phase4/admin/enterprise/groups/${form.group_id}/organizations`, { organization_id: Number(form.organization_id) });
      if (form.mode === 'GROUP_ACCEPT') await api.post(`/phase4/admin/enterprise/groups/${form.group_id}/accept`);
      if (form.mode === 'SITE_ASSIGNMENT') await api.post('/phase4/admin/enterprise/site-assignments', { site_id: Number(form.site_id), legal_entity_id: Number(form.legal_entity_id), relationship_type: form.relationship_type, effective_from: form.effective_from });
      toast.success('Enterprise structure updated'); setForm((current) => ({ ...INITIAL, mode: current.mode })); await onReload();
    } catch (error) { toast.error(error.response?.data?.message || 'Enterprise structure could not be updated.'); }
    finally { setSaving(false); }
  };

  const exportProjects = () => {
    const headings = ['Project', 'Site', 'Phases', 'Bookings', 'Booked value', 'Collections', 'Receivable', 'Actual cost', 'Committed cost', 'EAC', 'Filing issues', 'Registry backlog', 'Possession backlog'];
    const rows = (portfolio?.projects || []).map((project) => [project.name, project.site_name, project.phase_count, project.booking_count, project.booked_value, project.collections, project.receivable, project.actual_cost, project.committed_cost, project.estimate_at_completion, project.filing_issue_count, project.registry_backlog, project.possession_backlog]);
    const blob = new Blob([[headings, ...rows].map((row) => row.map(encodeCsvCell).join(',')).join('\n')], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `enterprise-portfolio-${new Date().toISOString().slice(0, 10)}.csv`; anchor.click(); URL.revokeObjectURL(url);
  };

  const modes = [['GROUP', 'Developer group'], ['ENTITY', 'Legal entity'], ['GROUP_INVITE', 'Invite organization'], ['GROUP_ACCEPT', 'Accept group invite'], ['SITE_ASSIGNMENT', 'Assign Site entity']];
  const summary = portfolio?.summary || {};
  const metrics = [['Sites', summary.sites], ['Projects', summary.projects], ['Phases', summary.phases], ['Bookings', summary.bookings], ['Booked', money(summary.booked_value)], ['Collections', money(summary.collections)], ['Receivable', money(summary.receivable)], ['EAC', money(summary.estimate_at_completion)]];

  return <div>
    <div className="grid xl:grid-cols-[0.72fr_1.28fr]">
      <form onSubmit={submit} className="border-b border-mr-line p-5 sm:p-7 xl:border-b-0 xl:border-r">
        <p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-mr-blue">Enterprise structure</p><h2 className="mt-2 text-xl font-semibold">Govern entities and scope</h2><p className="mt-1 text-[11px] leading-5 text-mr-muted">Group membership and Site ownership stay explicit, accepted, and effective-dated.</p>
        <div className="mt-6 space-y-4"><Field label="Action"><Select value={form.mode} onValueChange={(value) => update('mode', value)}><SelectTrigger className="h-11 rounded-control"><SelectValue /></SelectTrigger><SelectContent>{modes.map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field>
          {form.mode === 'GROUP' && <><Field label="Group code"><Input required value={form.group_code} onChange={(event) => update('group_code', event.target.value)} className="h-11 rounded-control" /></Field><Field label="Legal name"><Input required value={form.legal_name} onChange={(event) => update('legal_name', event.target.value)} className="h-11 rounded-control" /></Field></>}
          {form.mode === 'ENTITY' && <><Field label="Entity code"><Input required value={form.entity_code} onChange={(event) => update('entity_code', event.target.value)} className="h-11 rounded-control" /></Field><Field label="Legal name"><Input required value={form.legal_name} onChange={(event) => update('legal_name', event.target.value)} className="h-11 rounded-control" /></Field><Field label="Entity type"><Select value={form.entity_type} onValueChange={(value) => update('entity_type', value)}><SelectTrigger className="h-11 rounded-control"><SelectValue /></SelectTrigger><SelectContent>{['COMPANY', 'LLP', 'PARTNERSHIP', 'PROPRIETORSHIP', 'TRUST', 'SOCIETY', 'OTHER'].map((item) => <SelectItem key={item} value={item}>{title(item)}</SelectItem>)}</SelectContent></Select></Field><Field label="Developer group"><Select value={form.developer_group_id} onValueChange={(value) => update('developer_group_id', value)}><SelectTrigger className="h-11 rounded-control"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">No group</SelectItem>{ownedGroups.map((group) => <SelectItem key={group.id} value={String(group.id)}>{group.legal_name}</SelectItem>)}</SelectContent></Select></Field></>}
          {form.mode === 'GROUP_INVITE' && <><Field label="Owned developer group"><Select required value={form.group_id} onValueChange={(value) => update('group_id', value)}><SelectTrigger className="h-11 rounded-control"><SelectValue placeholder="Select group" /></SelectTrigger><SelectContent>{ownedGroups.map((group) => <SelectItem key={group.id} value={String(group.id)}>{group.legal_name}</SelectItem>)}</SelectContent></Select></Field><Field label="Organization ID"><Input required inputMode="numeric" value={form.organization_id} onChange={(event) => update('organization_id', event.target.value)} className="h-11 rounded-control" /></Field></>}
          {form.mode === 'GROUP_ACCEPT' && <Field label="Pending group invitation"><Select required value={form.group_id} onValueChange={(value) => update('group_id', value)}><SelectTrigger className="h-11 rounded-control"><SelectValue placeholder="Select invitation" /></SelectTrigger><SelectContent>{pendingGroups.map((group) => <SelectItem key={group.id} value={String(group.id)}>{group.legal_name}</SelectItem>)}</SelectContent></Select></Field>}
          {form.mode === 'SITE_ASSIGNMENT' && <><Field label="Site"><Select required value={form.site_id} onValueChange={(value) => update('site_id', value)}><SelectTrigger className="h-11 rounded-control"><SelectValue placeholder="Select Site" /></SelectTrigger><SelectContent>{sites.map((site) => <SelectItem key={site.id} value={String(site.id)}>{site.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Legal entity"><Select required value={form.legal_entity_id} onValueChange={(value) => update('legal_entity_id', value)}><SelectTrigger className="h-11 rounded-control"><SelectValue placeholder="Select entity" /></SelectTrigger><SelectContent>{(enterprise.legal_entities || []).map((entity) => <SelectItem key={entity.id} value={String(entity.id)}>{entity.legal_name}</SelectItem>)}</SelectContent></Select></Field><Field label="Relationship"><Select value={form.relationship_type} onValueChange={(value) => update('relationship_type', value)}><SelectTrigger className="h-11 rounded-control"><SelectValue /></SelectTrigger><SelectContent>{['PROJECT_OWNER', 'PROMOTER', 'DEVELOPER', 'LANDOWNER', 'OPERATING_ENTITY', 'OTHER'].map((item) => <SelectItem key={item} value={item}>{title(item)}</SelectItem>)}</SelectContent></Select></Field><Field label="Effective from"><Input required type="date" value={form.effective_from} onChange={(event) => update('effective_from', event.target.value)} className="h-11 rounded-control" /></Field></>}
        </div><Button disabled={saving} className="mt-6 h-11 rounded-full bg-mr-ink px-5"><Plus className="mr-2 h-4 w-4" />Apply controlled change</Button>
      </form>
      <div><div className="grid grid-cols-2 gap-5 border-b border-mr-line p-5 sm:grid-cols-4 sm:p-7">{metrics.map(([label, value]) => <div key={label}><p className="truncate text-lg font-semibold">{value || 0}</p><p className="text-[9px] uppercase tracking-[0.1em] text-mr-faint">{label}</p></div>)}</div><div className="divide-y divide-mr-line">{(enterprise.groups || []).map((group) => <div key={`g-${group.id}`} className="flex items-center gap-3 px-5 py-4 sm:px-7"><Network className="h-4 w-4 text-mr-blue" /><div className="min-w-0 flex-1"><p className="truncate text-[12px] font-semibold">{group.legal_name}</p><p className="text-[10px] text-mr-muted">{group.group_code} · {group.organizations?.length || 0} organizations</p></div><Badge variant="outline" className="rounded-full">{title(group.status)}</Badge></div>)}{(enterprise.legal_entities || []).map((entity) => <div key={`e-${entity.id}`} className="flex items-center gap-3 px-5 py-4 sm:px-7"><Building2 className="h-4 w-4 text-mr-lime-ink" /><div className="min-w-0 flex-1"><p className="truncate text-[12px] font-semibold">{entity.legal_name}</p><p className="text-[10px] text-mr-muted">{entity.entity_code} · {title(entity.entity_type)} · {entity.group_name || 'Independent'}</p></div></div>)}{!(enterprise.groups || []).length && !(enterprise.legal_entities || []).length && <div className="px-6 py-14 text-center text-[11px] text-mr-muted">No enterprise structure has been created.</div>}</div></div>
    </div>
    <section className="border-t border-mr-line"><div className="flex items-center justify-between gap-3 px-5 py-5 sm:px-7"><div><h2 className="text-[15px] font-semibold">Portfolio command centre</h2><p className="mt-1 text-[10px] text-mr-muted">Every aggregate includes source lineage and project drill-down.</p></div><Button variant="outline" size="sm" className="rounded-full" disabled={!portfolio?.projects?.length} onClick={exportProjects}><Download className="mr-2 h-3.5 w-3.5" />Export CSV</Button></div>
      {(portfolio?.risks || []).length > 0 && <div className="grid gap-3 border-y border-mr-line bg-mr-amber-soft/35 p-5 sm:grid-cols-2 sm:p-7">{portfolio.risks.map((risk) => <article key={risk.project_id} className="rounded-control border border-mr-amber/30 bg-mr-surface p-4"><div className="flex items-center gap-2"><AlertTriangle className="h-4 w-4 text-mr-amber-ink" /><p className="text-[12px] font-semibold">{risk.project_name}</p><Badge variant="outline" className="ml-auto rounded-full text-[9px]">{risk.severity}</Badge></div><p className="mt-2 text-[10px] leading-4 text-mr-muted">{risk.reasons.join(' · ')}</p><p className="mt-2 text-[10px] font-semibold text-mr-amber-ink">Next: {risk.next_action}</p></article>)}</div>}
      <div className="overflow-x-auto"><table className="min-w-[980px] w-full text-left"><thead className="border-b border-mr-line bg-mr-surface-2 text-[9px] uppercase tracking-[0.08em] text-mr-faint"><tr>{['Project', 'Progress', 'Bookings', 'Collections', 'Receivable', 'Actual', 'Committed', 'EAC', 'Exceptions', ''].map((label) => <th key={label} className="px-4 py-3 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y divide-mr-line">{(portfolio?.projects || []).map((project) => <tr key={project.id} className="text-[11px]"><td className="px-4 py-4"><p className="font-semibold">{project.name}</p><p className="text-[9px] text-mr-faint">{project.site_name} · {project.phase_count} phases</p></td><td className="px-4 py-4">{Number(project.construction_progress || 0).toFixed(1)}%<p className="text-[9px] text-mr-faint">cert. {project.certified_progress == null ? '—' : `${Number(project.certified_progress).toFixed(1)}%`}</p></td><td className="px-4 py-4">{project.booking_count}<p className="text-[9px] text-mr-faint">{money(project.booked_value)}</p></td><td className="px-4 py-4">{money(project.collections)}</td><td className="px-4 py-4">{money(project.receivable)}</td><td className="px-4 py-4">{money(project.actual_cost)}</td><td className="px-4 py-4">{money(project.committed_cost)}</td><td className="px-4 py-4">{money(project.estimate_at_completion)}</td><td className="px-4 py-4">{Number(project.filing_issue_count || 0) + Number(project.registry_backlog || 0) + Number(project.possession_backlog || 0)}</td><td className="px-4 py-4"><Button variant="ghost" size="icon" className="rounded-full" onClick={() => window.location.assign(`/rera?project_id=${project.id}`)} aria-label={`Open ${project.name}`}><ArrowUpRight className="h-4 w-4" /></Button></td></tr>)}{!portfolio?.projects?.length && <tr><td colSpan="10" className="px-6 py-14 text-center text-[11px] text-mr-muted">No canonical RERA projects are in this portfolio scope.</td></tr>}</tbody></table></div>
    </section>
  </div>;
}
